language: objective-c
osx_image: xcode11.3
xcode_workspace: Travis_CI_Demo/Travis_CI_Demo.xcworkspace
xcode_scheme: Travis_CI_Demo
os: osx

script:
  - xcodebuild test -project Travis_CI_Demo/Travis_CI_Demo.xcodeproj -scheme Travis_CI_Demo_Test -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator13.3 CODE_SIGNING_REQUIRED=NO
