language: objective-c
osx_image: xcode11.3
xcode_workspace: Travis_CI_Demo/Travis_CI_Demo.xcworkspace
xcode_scheme: Travis_CI_Demo
os: osx

script:
  - xcodebuild -project Travis_CI_Demo/Travis_CI_Demo.xcodeproj -scheme Travis_CI_Demo -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
  
jobs:
  include:
    - stage: CocoaPods
      osx_image: xcode11
      before_install:
      - gem install cocoapods
      - pod install --project-directory=Travis_CI_Demo
